from .runtime import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .image_history import NODE_CLASS_MAPPINGS as HISTORY_MAPPINGS
from .image_history import NODE_DISPLAY_NAME_MAPPINGS as HISTORY_DISPLAY_NAMES

NODE_CLASS_MAPPINGS.update(HISTORY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(HISTORY_DISPLAY_NAMES)

WEB_DIRECTORY = "./web"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']